"use client"

import { useParams } from 'next/navigation'
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export function PrivacyContent() {
  const params = useParams()
  const locale = params.locale as string
  const isZh = locale === 'zh'

  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold text-foreground mb-8">
            {isZh ? 'MeiHao 隐私政策' : 'MeiHao Privacy Policy'}
          </h1>
          <div className="prose prose-lg max-w-none">
            <p className="text-muted-foreground mb-8">
              {isZh ? '最后更新：2026年1月1日' : 'Last updated: January 1, 2026'}
            </p>
            
            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                {isZh ? '1. 引言' : '1. Introduction'}
              </h2>
              <p className="mb-4">
                {isZh
                  ? 'MeiHao（"我们"、"我们的"或"本服务"）非常重视用户的隐私保护。本隐私政策详细说明了我们如何收集、使用、存储和保护您在使用我们AI视频创作平台时的个人信息。'
                  : 'MeiHao ("we", "our", or "the service") takes user privacy protection very seriously. This privacy policy details how we collect, use, store, and protect your personal information when you use our AI video creation platform.'
                }
              </p>
              <p className="mb-4">
                {isZh 
                  ? '使用我们的服务即表示您同意按照本隐私政策处理您的信息。如果您不同意本政策，请停止使用我们的服务。'
                  : 'By using our services, you agree to the processing of your information in accordance with this privacy policy. If you do not agree with this policy, please stop using our services.'
                }
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                {isZh ? '2. 我们收集的信息' : '2. Information We Collect'}
              </h2>
              
              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '2.1 账户信息' : '2.1 Account Information'}
              </h3>
              <p className="mb-4">
                {isZh ? '当您注册账户时，我们收集：' : 'When you register an account, we collect:'}
              </p>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>{isZh ? '邮箱地址（用于账户验证和登录）' : 'Email address (for account verification and login)'}</li>
                <li>{isZh ? '用户名（可选）' : 'Username (optional)'}</li>
                <li>{isZh ? '密码（加密存储）' : 'Password (encrypted storage)'}</li>
                <li>{isZh ? '注册时间和最后登录时间' : 'Registration time and last login time'}</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '2.2 AI视频创作使用数据' : '2.2 AI Video Creation Usage Data'}
              </h3>
              <p className="mb-4">
                {isZh ? '为了提供AI视频创作服务，我们可能收集：' : 'To provide AI video creation services, we may collect:'}
              </p>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>
                  <strong>{isZh ? '输入描述' : 'Input Descriptions'}</strong>：
                  {isZh ? '您提供的视频内容描述、场景要求和创作指令' : 'Video content descriptions, scene requirements, and creation instructions you provide'}
                </li>
                <li>
                  <strong>{isZh ? '上传素材' : 'Uploaded Materials'}</strong>：
                  {isZh ? '您上传的图片、音频或其他用于视频创作的素材文件' : 'Images, audio, or other material files you upload for video creation'}
                </li>
                <li>
                  <strong>{isZh ? '生成视频' : 'Generated Videos'}</strong>：
                  {isZh ? 'AI为您生成的视频内容（临时存储用于服务优化）' : 'Video content generated by AI for you (temporarily stored for service optimization)'}
                </li>
                <li>
                  <strong>{isZh ? '使用统计' : 'Usage Statistics'}</strong>：
                  {isZh ? '视频生成次数、使用频率、参数偏好（如时长、比例、风格）' : 'Video generation count, usage frequency, parameter preferences (such as duration, aspect ratio, style)'}
                </li>
                <li>
                  <strong>{isZh ? '技术日志' : 'Technical Logs'}</strong>：
                  {isZh ? '视频生成处理时间、成功率、错误日志、性能数据' : 'Video generation processing time, success rate, error logs, performance data'}
                </li>
              </ul>

              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '2.3 技术信息' : '2.3 Technical Information'}
              </h3>
              <p className="mb-4">
                {isZh ? '我们自动收集的技术信息包括：' : 'Technical information we automatically collect includes:'}
              </p>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>{isZh ? 'IP地址和地理位置信息' : 'IP address and geographic location information'}</li>
                <li>{isZh ? '设备信息（浏览器类型、操作系统）' : 'Device information (browser type, operating system)'}</li>
                <li>{isZh ? '访问时间和页面浏览记录' : 'Access time and page browsing history'}</li>
                <li>{isZh ? '推荐来源网址' : 'Referrer URLs'}</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '2.4 支付信息' : '2.4 Payment Information'}
              </h3>
              <p className="mb-4">
                {isZh 
                  ? '对于付费服务，我们通过第三方支付处理商收集必要的支付信息。我们不直接存储您的完整信用卡信息。'
                  : 'For paid services, we collect necessary payment information through third-party payment processors. We do not directly store your complete credit card information.'
                }
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                {isZh ? '3. 信息使用方式' : '3. How We Use Information'}
              </h2>
              <p className="mb-4">
                {isZh ? '我们使用收集的信息用于：' : 'We use collected information for:'}
              </p>
              
              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '3.1 服务提供' : '3.1 Service Provision'}
              </h3>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>{isZh ? '提供AI视频创作服务，包括文本生视频、图生视频等功能' : 'Providing AI video creation services, including text-to-video, image-to-video, and other features'}</li>
                <li>{isZh ? '处理您的视频生成请求并创建个性化内容' : 'Processing your video generation requests and creating personalized content'}</li>
                <li>{isZh ? '维护账户安全和AI视频创作平台的服务稳定性' : 'Maintaining account security and the stability of the AI video creation platform'}</li>
                <li>{isZh ? '提供技术支持、创作指导和客户服务' : 'Providing technical support, creative guidance, and customer service'}</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '3.2 服务优化' : '3.2 Service Optimization'}
              </h3>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>{isZh ? '分析用户创作偏好和视频风格选择，改进AI视频生成模型的质量和准确性' : 'Analyzing user creative preferences and video style choices to improve the quality and accuracy of AI video generation models'}</li>
                <li>{isZh ? '开发新的视频创作功能、风格模板和AI模型' : 'Developing new video creation features, style templates, and AI models'}</li>
                <li>{isZh ? '优化用户界面、创作流程和视频预览体验' : 'Optimizing user interface, creation workflows, and video preview experiences'}</li>
                <li>{isZh ? '进行安全监控、内容审核和防止滥用AI生成技术的措施' : 'Conducting security monitoring, content moderation, and measures to prevent abuse of AI generation technology'}</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '3.3 法律合规' : '3.3 Legal Compliance'}
              </h3>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>{isZh ? '遵守适用的法律法规' : 'Complying with applicable laws and regulations'}</li>
                <li>{isZh ? '响应法律程序和政府要求' : 'Responding to legal processes and government requests'}</li>
                <li>{isZh ? '保护我们的权利和用户安全' : 'Protecting our rights and user safety'}</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                {isZh ? '4. 数据安全' : '4. Data Security'}
              </h2>
              <p className="mb-4">
                {isZh ? '我们采用行业标准的安全措施保护您的信息：' : 'We employ industry-standard security measures to protect your information:'}
              </p>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>
                  <strong>{isZh ? '加密传输' : 'Encrypted Transmission'}</strong>：
                  {isZh ? '使用SSL/TLS协议加密所有数据传输' : 'Using SSL/TLS protocols to encrypt all data transmission'}
                </li>
                <li>
                  <strong>{isZh ? '加密存储' : 'Encrypted Storage'}</strong>：
                  {isZh ? '敏感数据采用AES-256加密存储' : 'Sensitive data stored using AES-256 encryption'}
                </li>
                <li>
                  <strong>{isZh ? '访问控制' : 'Access Control'}</strong>：
                  {isZh ? '严格限制数据访问权限' : 'Strictly limiting data access permissions'}
                </li>
                <li>
                  <strong>{isZh ? '安全监控' : 'Security Monitoring'}</strong>：
                  {isZh ? '7×24小时安全监控和威胁检测' : '24/7 security monitoring and threat detection'}
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                {isZh ? '5. 您的权利' : '5. Your Rights'}
              </h2>
              <p className="mb-4">
                {isZh ? '您对自己的个人信息享有以下权利：' : 'You have the following rights regarding your personal information:'}
              </p>
              
              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '5.1 访问和查看' : '5.1 Access and View'}
              </h3>
              <p className="mb-4">
                {isZh ? '您可以随时查看我们收集的关于您的信息。' : 'You can view information we have collected about you at any time.'}
              </p>

              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '5.2 更正和更新' : '5.2 Correction and Update'}
              </h3>
              <p className="mb-4">
                {isZh ? '您可以更新或更正您的账户信息。' : 'You can update or correct your account information.'}
              </p>

              <h3 className="text-xl font-semibold mb-3">
                {isZh ? '5.3 删除' : '5.3 Deletion'}
              </h3>
              <p className="mb-4">
                {isZh ? '您可以要求删除您的账户和相关数据。某些信息可能因法律要求而保留。' : 'You can request deletion of your account and related data. Some information may be retained due to legal requirements.'}
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                {isZh ? '6. 联系我们' : '6. Contact Us'}
              </h2>
              <p className="mb-4">
                {isZh 
                  ? '如果您对本隐私政策有任何疑问或需要行使您的权利，请联系我们：'
                  : 'If you have any questions about this privacy policy or need to exercise your rights, please contact us:'
                }
              </p>
              <ul className="list-disc list-inside mb-4 space-y-2">
                <li>{isZh ? '邮箱：app@itusi.cn' : 'Email: app@itusi.cn'}</li>
                <li>{isZh ? '网站：https://meihao.com' : 'Website: https://meihao.com'}</li>
              </ul>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
} 